version: '3.9'

services:

  frontend:
    build: .
    container_name: frontend
    restart: unless-stopped
    image: frontend
    networks:
      - traefik-proxy
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M  

networks:
  traefik-proxy:
    external: true
    




